import type { Article } from "./types";

export const bancaArticles: Article[] = [
  {
    slug: "abrir-cuenta-bancaria-sin-ssn",
    seoTitle: "Abrir cuenta bancaria sin SSN: guía 2026",
    title: "Cómo abrir una cuenta bancaria sin SSN en EE.UU.",
    description: "Aprende cómo abrir una cuenta bancaria sin Seguro Social: documentos que aceptan, ITIN, matrícula consular, ChexSystems y comisiones.",
    category: "banca", readMinutes: 8, date: "2026-08-25",
    keywords: ["abrir cuenta bancaria sin SSN", "cuenta de banco con ITIN", "banco para inmigrantes", "second chance checking en español"],
  },
  {
    slug: "diferencia-ssn-itin",
    seoTitle: "Diferencia entre SSN e ITIN: guía clara 2026",
    title: "Diferencia entre SSN e ITIN: qué es cada uno y para qué sirve",
    description: "Entiende la diferencia entre SSN e ITIN, qué puedes hacer con cada número y por qué tener ITIN no autoriza a trabajar.",
    category: "banca", readMinutes: 12, date: "2026-09-05",
    keywords: ["diferencia SSN e ITIN", "SSN vs ITIN cuál necesito", "qué es el ITIN", "ITIN empieza por 9", "puedo trabajar con ITIN"],
  },
  {
    slug: "mejores-bancos-para-hispanos",
    seoTitle: "Mejores bancos para hispanos e inmigrantes 2026",
    title: "Mejores bancos para hispanos e inmigrantes en EE.UU.",
    description: "Comparamos bancos y credit unions para hispanos e inmigrantes según ITIN, atención en español, comisiones y remesas.",
    category: "banca", readMinutes: 12, date: "2026-09-05",
    keywords: ["mejores bancos para hispanos", "banco en español EE.UU.", "banco que acepta ITIN", "cuenta sin cuota mensual inmigrantes", "Juntos Avanzamos credit union"],
  },
  {
    slug: "enviar-dinero-latinoamerica",
    seoTitle: "Cómo enviar dinero a Latinoamérica sin pagar de más",
    title: "Cómo enviar dinero a Latinoamérica: mejores apps y menores comisiones",
    description: "Compara cómo enviar dinero desde EE.UU. a Latinoamérica: comisión, tipo de cambio, forma de entrega y costo total.",
    category: "banca", readMinutes: 6, date: "2026-01-27",
    keywords: ["enviar dinero a Latinoamérica", "mejores apps de remesas", "mandar dinero barato a México", "cómo enviar remesas desde Estados Unidos"],
  },
  {
    slug: "sacar-licencia-conducir",
    seoTitle: "Cómo sacar la licencia de conducir en EE.UU. 2026",
    title: "Cómo sacar la licencia de conducir en EE.UU. paso a paso",
    description: "Guía paso a paso para obtener licencia de conducir en Estados Unidos, incluidos estados con opciones para inmigrantes.",
    category: "banca", readMinutes: 11, date: "2026-09-05",
    keywords: ["sacar licencia de conducir EE.UU.", "licencia de manejo para inmigrantes", "cómo obtener licencia de conducir", "estados que dan licencia sin papeles 2026", "licencia de conducir sin seguro social"],
  },
  {
    slug: "abrir-cuenta-con-matricula-consular",
    seoTitle: "Abrir cuenta con matrícula consular: paso a paso",
    title: "Cómo abrir una cuenta bancaria con matrícula consular",
    description: "Cómo abrir una cuenta bancaria con matrícula consular, qué documentos llevar y qué hacer si una sucursal te rechaza.",
    category: "banca", readMinutes: 8, date: "2026-08-25",
    keywords: ["abrir cuenta con matrícula consular", "cómo sacar la matrícula consular", "renovar matrícula consular", "matrícula consular banco"],
  },
  {
    slug: "enviar-dinero-guatemala",
    seoTitle: "Enviar dinero a Guatemala: apps y comisiones 2026",
    title: "Enviar dinero a Guatemala: mejores apps y cómo pagar menos (2026)",
    description: "Compara apps para enviar dinero a Guatemala y aprende a medir comisión, tipo de cambio, entrega y costo total.",
    category: "banca", readMinutes: 9, date: "2026-08-22",
    keywords: ["enviar dinero a Guatemala", "remesas a Guatemala barato", "mejor app para enviar dinero a Guatemala", "tipo de cambio quetzal remesas"],
  },
  {
    slug: "enviar-dinero-honduras",
    seoTitle: "Enviar dinero a Honduras: apps y comisiones 2026",
    title: "Enviar dinero a Honduras: mejores apps y cómo pagar menos (2026)",
    description: "Compara opciones para enviar remesas a Honduras y revisa comisión, tipo de cambio del lempira y forma de entrega.",
    category: "banca", readMinutes: 9, date: "2026-08-22",
    keywords: ["enviar dinero a Honduras", "remesas a Honduras barato", "mejor app para enviar dinero a Honduras", "tipo de cambio lempira remesas"],
  },
  {
    slug: "enviar-dinero-el-salvador",
    seoTitle: "Enviar dinero a El Salvador: comisiones 2026",
    title: "Enviar dinero a El Salvador: comisiones y mejores apps (2026)",
    description: "Compara las mejores opciones para enviar dinero a El Salvador, donde el dólar elimina el riesgo de tipo de cambio pero no las comisiones.",
    category: "banca", readMinutes: 8, date: "2026-08-22",
    keywords: ["enviar dinero a El Salvador", "remesas a El Salvador barato", "mejor app para enviar dinero a El Salvador", "comisiones remesas El Salvador"],
  },
  {
    slug: "bancos-que-aceptan-matricula-consular",
    seoTitle: "Bancos que aceptan matrícula consular (lista 2026)",
    title: "Qué bancos aceptan matrícula consular en EE.UU. (lista 2026)",
    description: "Lista y guía para saber qué bancos aceptan matrícula consular, qué documentos llevar y cómo evitar un rechazo por falta de SSN.",
    category: "banca", readMinutes: 11, date: "2026-09-05",
    keywords: ["bancos que aceptan matrícula consular", "qué banco acepta matrícula consular", "banco para inmigrantes sin SSN", "cooperativas de crédito para hispanos", "matrícula consular vigencia 5 años", "U.S. Bank matrícula consular"],
  },
  {
    slug: "enviar-dinero-a-mexico",
    seoTitle: "Enviar dinero a México: mejores apps y cómo pagar menos 2026",
    title: "Enviar dinero a México: mejores apps y cómo pagar menos (2026)",
    description: "Compara apps para enviar dinero de EE.UU. a México y aprende a calcular comisión, tipo de cambio, impuesto y cuánto recibe tu familia.",
    category: "banca", readMinutes: 9, date: "2026-08-02",
    keywords: ["enviar dinero a México", "mejores apps para enviar dinero a México", "remesas a México barato", "tipo de cambio remesas México", "cómo mandar dinero a México desde Estados Unidos"],
  },
  {
    slug: "enviar-dinero-colombia-ecuador",
    seoTitle: "Enviar dinero a Colombia y Ecuador: costos y apps",
    title: "Enviar dinero a Colombia y Ecuador: guía de costos y mejores apps",
    description: "Compara costos para enviar dinero a Colombia y Ecuador y entiende cómo influyen el tipo de cambio, la entrega y la comisión.",
    category: "banca", readMinutes: 8, date: "2026-08-04",
    keywords: ["enviar dinero a Colombia", "enviar dinero a Ecuador", "remesas Colombia barato", "enviar dinero a Nequi desde EE.UU."],
  },
  {
    slug: "enviar-dinero-republica-dominicana",
    seoTitle: "Enviar dinero a República Dominicana: mejores opciones 2026",
    title: "Enviar dinero a República Dominicana: comisiones y mejores opciones",
    description: "Compara comisiones y tipo de cambio para enviar remesas a República Dominicana y descubre qué opción conviene según el monto.",
    category: "banca", readMinutes: 9, date: "2026-08-07",
    keywords: ["enviar dinero a República Dominicana", "remesas RD barato", "mejor app enviar dinero a Dominicana", "tipo de cambio peso dominicano remesas"],
  },
  {
    slug: "enviar-dinero-venezuela",
    seoTitle: "Enviar dinero a Venezuela: cómo hacerlo seguro",
    title: "Enviar dinero a Venezuela: cómo hacerlo seguro y sin perder valor",
    description: "Qué opciones existen para enviar dinero a Venezuela, cómo comparar costos y cómo proteger a la persona que recibe la remesa.",
    category: "banca", readMinutes: 9, date: "2026-08-08",
    keywords: ["enviar dinero a Venezuela", "remesas Venezuela seguras", "mandar dólares a Venezuela", "mejor forma enviar dinero Venezuela"],
  },
];
