import type { Article } from "./types";

export const segurosArticles: Article[] = [
  {
    slug: "seguro-de-auto-sin-licencia-americana",
    seoTitle: "Seguro de auto sin licencia de EE.UU.: guía 2026",
    title: "Cómo conseguir seguro de auto sin licencia de EE.UU.",
    description: "Opciones para asegurar tu carro cuando todavía no tienes licencia de EE.UU.: licencia extranjera, conductor excluido y alternativas según el estado.",
    category: "seguro-de-auto", readMinutes: 12, date: "2026-09-02",
    keywords: ["seguro de auto sin licencia", "asegurar carro sin licencia americana", "seguro para dueño de carro sin licencia", "licencia extranjera seguro de auto", "conductor excluido poliza", "seguro de auto sin licencia por estado", "asegurar carro con licencia de otro país"],
  },
  {
    slug: "seguro-de-auto-con-itin",
    seoTitle: "Seguro de auto con ITIN: cómo asegurarte sin SSN | 2026",
    title: "Seguro de auto con ITIN: cómo asegurar tu carro sin Seguro Social",
    description: "Aprende cómo cotizar seguro de auto con ITIN, qué documentos e información puede pedir la aseguradora y qué revisar antes de elegir una póliza.",
    category: "seguro-de-auto", readMinutes: 10, date: "2026-08-23",
    keywords: ["seguro de auto con ITIN", "aseguranza con ITIN", "seguro de auto sin seguro social", "asegurar carro con ITIN", "cotizar seguro auto sin SSN", "seguro de carro con ITIN", "aseguradora acepta ITIN"],
  },
  {
    slug: "seguro-de-auto-barato-hispanos",
    seoTitle: "Cómo conseguir seguro de auto barato en EE.UU. 2026",
    title: "Cómo conseguir seguro de auto barato en EE.UU. (guía práctica)",
    description: "Cómo comparar cotizaciones, coberturas y descuentos para buscar un seguro de auto más barato en EE.UU. sin sacrificar la protección que necesitas.",
    category: "seguro-de-auto", readMinutes: 13, date: "2026-09-01",
    keywords: ["seguro de auto barato", "cómo bajar el seguro del carro", "seguro económico EE.UU.", "descuentos en seguro de auto", "seguro de auto por millas"],
  },
  {
    slug: "que-hacer-accidente-sin-seguro",
    seoTitle: "Accidente de auto sin seguro: qué hacer paso a paso",
    title: "Qué hacer si tienes un accidente de auto sin seguro",
    description: "Pasos que conviene seguir después de un accidente cuando no tienes seguro, cómo documentar lo ocurrido y qué consecuencias pueden existir según el estado.",
    category: "seguro-de-auto", readMinutes: 12, date: "2026-09-01",
    keywords: ["accidente sin seguro", "qué hacer si choco sin seguro", "conducir sin seguro EE.UU.", "multa por manejar sin seguro", "leyes no pay no play"],
  },
  {
    slug: "cobertura-minima-vs-completa",
    seoTitle: "Cobertura mínima vs. completa de auto: ¿cuál necesitas?",
    title: "Cobertura mínima vs completa: ¿cuál seguro de auto necesitas?",
    description: "Entiende liability, colisión y otras coberturas para decidir cuánto seguro de auto necesitas y evitar pagar por protección que no te conviene.",
    category: "seguro-de-auto", readMinutes: 12, date: "2026-09-01",
    keywords: ["cobertura mínima vs completa", "tipos de seguro de auto", "liability vs full coverage", "qué cubre el seguro de auto", "cobertura UM UIM qué es"],
  },
  {
    slug: "seguro-de-auto-con-matricula-consular",
    seoTitle: "Seguro de auto con matrícula consular: guía 2026",
    title: "Seguro de auto con matrícula consular: cómo asegurarte sin licencia de EE.UU.",
    description: "Qué revisar si quieres asegurar un carro con matrícula consular, pasaporte o licencia extranjera y cómo comparar correctamente las cotizaciones.",
    category: "seguro-de-auto", readMinutes: 12, date: "2026-09-02",
    keywords: ["seguro de auto con matrícula consular", "aseguranza con matrícula consular", "matrícula consular aseguranza Texas", "broker fee seguro de auto", "seguro auto con pasaporte mexicano", "cómo asegurar carro con matrícula consular", "aseguranza sin licencia con pasaporte"],
  },
  {
    slug: "seguro-de-auto-california-inmigrantes",
    seoTitle: "Seguro de auto en California para inmigrantes 2026",
    title: "Seguro de auto en California para inmigrantes: mínimos 30/60/15 y licencia AB 60",
    description: "Requisitos para asegurar un vehículo en California, límites de responsabilidad, licencia AB 60 y opciones para comparar precios.",
    category: "seguro-de-auto", readMinutes: 13, date: "2026-08-26",
    keywords: ["seguro de auto California inmigrantes", "licencia AB 60 seguro", "mínimos de seguro California 30/60/15", "seguro de auto barato California", "CLCA seguro de bajo costo California", "Proposición 213 California sin seguro"],
  },
  {
    slug: "seguro-de-auto-texas-inmigrantes",
    seoTitle: "Seguro de auto en Texas para inmigrantes 2026",
    title: "Seguro de auto en Texas para inmigrantes: 30/60/25 sin licencia estatal",
    description: "Qué debes revisar para asegurar un carro en Texas, los límites de responsabilidad y las opciones disponibles si utilizas ITIN o licencia extranjera.",
    category: "seguro-de-auto", readMinutes: 12, date: "2026-08-26",
    keywords: ["seguro de auto Texas inmigrantes", "seguro de auto Texas sin licencia", "30/60/25 Texas", "seguro de auto con ITIN Texas", "multa por manejar sin seguro en Texas", "TexasSure verificación de seguro"],
  },
  {
    slug: "seguro-de-auto-florida-inmigrantes",
    seoTitle: "Seguro de auto en Florida para inmigrantes 2026",
    title: "Seguro de auto en Florida para inmigrantes: PIP, no-fault y el riesgo del mínimo legal",
    description: "Cómo funcionan PIP y la cobertura mínima en Florida, qué protección adicional puedes considerar y cómo comparar el costo de tu póliza.",
    category: "seguro-de-auto", readMinutes: 12, date: "2026-08-26",
    keywords: ["seguro de auto Florida inmigrantes", "PIP Florida seguro", "seguro de auto Florida sin licencia", "seguro no-fault Florida", "regla de los 14 días PIP Florida", "FR-44 Florida requisitos"],
  },
  {
    slug: "seguro-de-auto-nueva-york-inmigrantes",
    seoTitle: "Seguro de auto en Nueva York para inmigrantes 2026",
    title: "Seguro de auto en Nueva York para inmigrantes: Green Light Law y mínimos 25/50/10",
    description: "Requisitos de seguro de auto en Nueva York, Green Light Law, cobertura no-fault y puntos clave para comparar pólizas.",
    category: "seguro-de-auto", readMinutes: 12, date: "2026-08-26",
    keywords: ["seguro de auto Nueva York inmigrantes", "Green Light Law licencia", "mínimos de seguro Nueva York 25/50/10", "PIP Nueva York", "multa por no tener seguro en Nueva York", "seguro de auto barato Nueva York"],
  },
  {
    slug: "seguro-de-vida-para-hispanos",
    seoTitle: "Seguro de vida para hispanos con ITIN: guía 2026",
    title: "Seguro de vida para hispanos: guía completa 2026 (con ITIN)",
    description: "Qué revisar al buscar seguro de vida con ITIN, diferencias entre term y whole life, costos y cómo calcular una cobertura adecuada para tu familia.",
    category: "seguro-de-auto", readMinutes: 13, date: "2026-08-26",
    keywords: ["seguro de vida para hispanos", "seguro de vida con ITIN", "seguro de vida sin seguro social", "cuánto cuesta un seguro de vida", "term life vs whole life"],
  },
  {
    slug: "seguro-de-auto-illinois-inmigrantes",
    seoTitle: "Seguro de auto en Illinois para inmigrantes 2026",
    title: "Seguro de auto en Illinois para inmigrantes: requisitos y precios 2026",
    description: "Requisitos para asegurar un carro en Illinois, límites de responsabilidad y puntos que pueden afectar el precio de tu póliza.",
    category: "seguro-de-auto", readMinutes: 12, date: "2026-09-02",
    keywords: ["seguro de auto Illinois", "seguro de auto Chicago hispanos", "licencia de manejo Illinois sin papeles", "requisitos seguro auto Illinois", "licencia estándar Illinois HB 3882", "seguro de auto Chicago barato"],
  },
  {
    slug: "seguro-de-auto-arizona-inmigrantes",
    seoTitle: "Seguro de auto en Arizona para inmigrantes 2026",
    title: "Seguro de auto en Arizona para inmigrantes: requisitos y precios 2026",
    description: "Qué debes revisar para asegurar un carro en Arizona, los límites de responsabilidad y cómo comparar opciones en Phoenix y Tucson.",
    category: "seguro-de-auto", readMinutes: 12, date: "2026-09-02",
    keywords: ["seguro de auto Arizona", "seguro de auto Phoenix hispanos", "seguro sin licencia Arizona", "requisitos seguro auto Arizona", "seguro de auto Phoenix precios", "límite de propiedad 15000 Arizona"],
  },
  {
    slug: "seguro-de-casa-y-renta-inmigrantes",
    seoTitle: "Seguro de renta y casa para inmigrantes: qué cubre",
    title: "Seguro de renta y de casa para inmigrantes: qué cubre y cuánto cuesta",
    description: "Qué cubre el renters insurance, qué diferencia hay con el seguro de vivienda y qué debes comparar antes de contratar una póliza.",
    category: "seguro-de-auto", readMinutes: 13, date: "2026-09-02",
    keywords: ["seguro de renta para inmigrantes", "renters insurance en español", "seguro de casa con ITIN", "cuánto cuesta seguro de renta", "seguro de inquilinos cuánto cuesta", "replacement cost vs actual cash value"],
  },
  {
    slug: "seguro-de-auto-georgia-inmigrantes",
    seoTitle: "Seguro de auto en Georgia para inmigrantes 2026",
    title: "Seguro de auto en Georgia para inmigrantes: requisitos y precios 2026",
    description: "Requisitos para asegurar un carro en Georgia, límites de responsabilidad, verificación electrónica y factores que influyen en el precio.",
    category: "seguro-de-auto", readMinutes: 13, date: "2026-09-02",
    keywords: ["seguro de auto en Georgia", "seguro de carro Georgia sin licencia", "requisitos seguro auto Georgia", "seguro con ITIN Georgia", "GEICS Georgia verificación de seguro", "seguro de auto Atlanta"],
  },
  {
    slug: "seguro-de-auto-nevada-inmigrantes",
    seoTitle: "Seguro de auto en Nevada para inmigrantes 2026",
    title: "Seguro de auto en Nevada para inmigrantes: requisitos y precios 2026",
    description: "Requisitos para asegurar tu carro en Nevada, límites de responsabilidad, documentación y puntos que pueden afectar el costo de la póliza.",
    category: "seguro-de-auto", readMinutes: 12, date: "2026-09-02",
    keywords: ["seguro de auto en Nevada", "Driver Authorization Card Nevada", "requisitos seguro auto Nevada", "seguro de carro Las Vegas inmigrantes", "seguro de auto Las Vegas 2026", "verificación electrónica de seguro Nevada"],
  },
  {
    slug: "seguro-de-auto-carolina-del-norte-inmigrantes",
    seoTitle: "Seguro de auto en Carolina del Norte: límites 2026",
    title: "Seguro de auto en Carolina del Norte: nuevos límites 50/100/50",
    description: "Qué debes revisar sobre los límites de responsabilidad y otras coberturas al asegurar un vehículo en Carolina del Norte.",
    category: "seguro-de-auto", readMinutes: 14, date: "2026-09-02",
    keywords: ["seguro de auto Carolina del Norte", "límites 50/100/50 North Carolina", "seguro de carro NC inmigrantes", "requisitos seguro auto Carolina del Norte", "formulario DL-123 Carolina del Norte", "Safe Driver Incentive Plan"],
  },
  {
    slug: "que-es-sr22-como-funciona",
    seoTitle: "¿Qué es un SR-22 y cómo funciona? Guía 2026",
    title: "¿Qué es un SR-22 y cómo funciona? Guía clara en español",
    description: "El SR-22 no es un seguro: es un certificado que tu aseguradora presenta al estado. Cuándo lo necesitas, cómo afecta tu póliza y por cuánto tiempo puede exigirse.",
    category: "seguro-de-auto", readMinutes: 13, date: "2026-09-01",
    keywords: ["qué es un SR-22", "seguro SR22 en español", "SR-22 cuánto cuesta", "cómo obtener SR22", "SR22 sin licencia", "SR22 con ITIN"],
  },
  {
    slug: "seguro-de-salud-para-inmigrantes",
    seoTitle: "Seguro de salud para inmigrantes en EE.UU.: opciones 2026",
    title: "Seguro de salud para inmigrantes: opciones según tu estatus",
    description: "Opciones de cobertura médica para inmigrantes en EE.UU., incluyendo Marketplace, Medicaid, CHIP y alternativas para quienes no califican.",
    category: "seguro-de-auto", readMinutes: 14, date: "2026-08-26",
    keywords: ["seguro de salud para inmigrantes", "seguro médico para inmigrantes", "seguro de salud con ITIN", "Obamacare inmigrantes", "Marketplace inmigrantes", "Medicaid inmigrantes"],
  },
  {
    slug: "seguro-de-auto-colorado-inmigrantes",
    seoTitle: "Seguro de auto en Colorado para inmigrantes 2026",
    title: "Seguro de auto en Colorado para inmigrantes: SB 251, granizo y mínimos",
    description: "Requisitos de seguro de auto en Colorado, límites obligatorios, SB 251 y coberturas importantes por granizo y clima.",
    category: "seguro-de-auto", readMinutes: 13, date: "2026-09-02",
    keywords: ["seguro de auto Colorado inmigrantes", "SB 251 Colorado seguro", "mínimos seguro Colorado", "seguro auto Denver hispanos", "granizo seguro auto Colorado", "seguro de auto con ITIN Colorado"],
  },
  {
    slug: "seguro-de-auto-washington-inmigrantes",
    seoTitle: "Seguro de auto en Washington para inmigrantes 2026",
    title: "Seguro de auto en Washington para inmigrantes: mínimos y PIP",
    description: "Qué exige Washington para asegurar un vehículo, cómo funciona PIP y qué opciones considerar si eres inmigrante o tienes documentación alternativa.",
    category: "seguro-de-auto", readMinutes: 13, date: "2026-09-02",
    keywords: ["seguro de auto Washington inmigrantes", "mínimos seguro Washington", "PIP Washington seguro auto", "seguro auto Seattle hispanos", "seguro con ITIN Washington"],
  },
  {
    slug: "seguro-de-auto-new-jersey-inmigrantes",
    seoTitle: "Seguro de auto en New Jersey para inmigrantes 2026",
    title: "Seguro de auto en New Jersey para inmigrantes: nuevos mínimos 2026",
    description: "Los requisitos de seguro de auto en New Jersey, cambios de 2026, límites de responsabilidad y puntos clave para comparar una póliza.",
    category: "seguro-de-auto", readMinutes: 13, date: "2026-09-02",
    keywords: ["seguro de auto New Jersey inmigrantes", "nuevos mínimos seguro New Jersey 2026", "seguro auto NJ hispanos", "seguro de auto con ITIN New Jersey", "requisitos seguro New Jersey"],
  },
];
