import type { Article } from "./types";

export const segurosArticles: Article[] = [
  {
    slug: "seguro-de-auto-sin-licencia-americana",
    seoTitle: "Seguro de auto sin licencia de EE.UU.: guía 2026",
    title: "Cómo conseguir seguro de auto sin licencia de EE.UU.",
    description:
      "Las tres rutas legales para asegurar tu carro sin licencia americana: licencia extranjera, conductor excluido o sacar la estatal. Precios reales de 2026.",
    category: "seguro-de-auto",
    readMinutes: 12,
    date: "2026-09-02",
    keywords: [
      "seguro de auto sin licencia",
      "asegurar carro sin licencia americana",
      "seguro para dueño de carro sin licencia",
      "licencia extranjera seguro de auto",
      "conductor excluido poliza",
      "seguro de auto sin licencia por estado",
      "asegurar carro con licencia de otro país",
    ],
  },
  {
    slug: "seguro-de-auto-con-itin",
    seoTitle: "Seguro de auto con ITIN: asegura tu carro sin SSN",
    title: "Seguro de auto con ITIN: cómo asegurar tu carro sin Seguro Social",
    description:
      "Qué ve la aseguradora con tu ITIN, cómo cotizar cuando el formulario exige SSN y por qué tener ITIN abarata tu prima a medio plazo. Datos de 2026.",
    category: "seguro-de-auto",
    readMinutes: 10,
    date: "2026-08-23",
    keywords: [
      "seguro de auto con ITIN",
      "aseguranza con ITIN",
      "seguro de auto sin seguro social",
      "asegurar carro con ITIN",
      "cotizar seguro auto sin SSN",
    ],
  },
  {
    slug: "seguro-de-auto-barato-hispanos",
    seoTitle: "Cómo conseguir seguro de auto barato en EE.UU.",
    title: "Cómo conseguir seguro de auto barato en EE.UU. (guía práctica)",
    description:
      "12 estrategias comprobadas para bajar el costo de tu seguro de auto en Estados Unidos, especialmente si eres nuevo conductor o inmigrante.",
    category: "seguro-de-auto",
    readMinutes: 13,
    date: "2026-09-01",
    keywords: [
      "seguro de auto barato",
      "cómo bajar el seguro del carro",
      "seguro económico EE.UU.",
      "descuentos en seguro de auto",
      "seguro de auto por millas",
    ],
  },
  {
    slug: "que-hacer-accidente-sin-seguro",
    title: "Qué hacer si tienes un accidente de auto sin seguro",
    description:
      "Pasos exactos que debes seguir si chocas y no tienes seguro en EE.UU., cómo proteger tus derechos y qué consecuencias evitar.",
    category: "seguro-de-auto",
    readMinutes: 12,
    date: "2026-09-01",
    keywords: [
      "accidente sin seguro",
      "qué hacer si choco sin seguro",
      "conducir sin seguro EE.UU.",
      "multa por manejar sin seguro",
      "leyes no pay no play",
    ],
  },
  {
    slug: "cobertura-minima-vs-completa",
    seoTitle: "Cobertura mínima vs completa: ¿cuál necesitas?",
    title: "Cobertura mínima vs completa: ¿cuál seguro de auto necesitas?",
    description:
      "Entiende la diferencia entre liability, colisión y cobertura completa para elegir el seguro correcto y no pagar de más.",
    category: "seguro-de-auto",
    readMinutes: 12,
    date: "2026-09-01",
    keywords: [
      "cobertura mínima vs completa",
      "tipos de seguro de auto",
      "liability vs full coverage",
      "qué cubre el seguro de auto",
      "cobertura UM UIM qué es",
    ],
  },
  {
    slug: "seguro-de-auto-con-matricula-consular",
    seoTitle: "Seguro de auto con matrícula consular: guía 2026",
    title: "Seguro de auto con matrícula consular: cómo asegurarte sin licencia de EE.UU.",
    description:
      "En qué estados funciona la matrícula consular para asegurar tu carro, qué agencias la aceptan y cómo evitar el broker fee que no te cotizan.",
    category: "seguro-de-auto",
    readMinutes: 12,
    date: "2026-09-02",
    keywords: [
      "seguro de auto con matrícula consular",
      "aseguranza con matrícula consular",
      "matrícula consular aseguranza Texas",
      "broker fee seguro de auto",
      "seguro auto con pasaporte mexicano",
      "cómo asegurar carro con matrícula consular",
      "aseguranza sin licencia con pasaporte",
    ],
  },
  {
    slug: "seguro-de-auto-california-inmigrantes",
    seoTitle: "Seguro de auto en California para inmigrantes 2026",
    title: "Seguro de auto en California para inmigrantes: mínimos 30/60/15 y licencia AB 60",
    description:
      "California subió sus mínimos a 30/60/15 y emite licencia AB 60 sin importar tu estatus. Requisitos, precios reales y cómo pagar menos.",
    category: "seguro-de-auto",
    readMinutes: 13,
    date: "2026-08-26",
    keywords: [
      "seguro de auto California inmigrantes",
      "licencia AB 60 seguro",
      "mínimos de seguro California 30/60/15",
      "seguro de auto barato California",
      "CLCA seguro de bajo costo California",
      "Proposición 213 California sin seguro",
    ],
  },
  {
    slug: "seguro-de-auto-texas-inmigrantes",
    seoTitle: "Seguro de auto en Texas para inmigrantes 2026",
    title: "Seguro de auto en Texas para inmigrantes: 30/60/25 sin licencia estatal",
    description:
      "Texas exige seguro 30/60/25 pero no da licencia sin estatus legal. Cómo asegurar tu carro con ITIN o licencia extranjera y qué evitar.",
    category: "seguro-de-auto",
    readMinutes: 12,
    date: "2026-08-26",
    keywords: [
      "seguro de auto Texas inmigrantes",
      "seguro de auto Texas sin licencia",
      "30/60/25 Texas",
      "seguro de auto con ITIN Texas",
      "multa por manejar sin seguro en Texas",
      "TexasSure verificación de seguro",
    ],
  },
  {
    slug: "seguro-de-auto-florida-inmigrantes",
    seoTitle: "Seguro de auto en Florida para inmigrantes (PIP 2026)",
    title: "Seguro de auto en Florida para inmigrantes: PIP, no-fault y el riesgo del mínimo legal",
    description:
      "Florida pide $10,000 PIP y $10,000 PDL, pero el mínimo no cubre lesiones a terceros. Qué necesitas realmente y cómo bajar la prima.",
    category: "seguro-de-auto",
    readMinutes: 12,
    date: "2026-08-26",
    keywords: [
      "seguro de auto Florida inmigrantes",
      "PIP Florida seguro",
      "seguro de auto Florida sin licencia",
      "seguro no-fault Florida",
      "regla de los 14 días PIP Florida",
      "FR-44 Florida requisitos",
    ],
  },
  {
    slug: "seguro-de-auto-nueva-york-inmigrantes",
    seoTitle: "Seguro de auto en Nueva York para inmigrantes 2026",
    title: "Seguro de auto en Nueva York para inmigrantes: Green Light Law y mínimos 25/50/10",
    description:
      "En Nueva York puedes tener licencia sin importar tu estatus. Mínimos legales, PIP de $50,000, plazos de no-fault y cómo pagar menos.",
    category: "seguro-de-auto",
    readMinutes: 12,
    date: "2026-08-26",
    keywords: [
      "seguro de auto Nueva York inmigrantes",
      "Green Light Law licencia",
      "mínimos de seguro Nueva York 25/50/10",
      "PIP Nueva York",
      "multa por no tener seguro en Nueva York",
      "seguro de auto barato Nueva York",
    ],
  },
  {
    slug: "seguro-de-vida-para-hispanos",
    title: "Seguro de vida para hispanos: guía completa 2026 (con ITIN)",
    description:
      "Cómo comprar seguro de vida en EE.UU. sin SSN, cuánto cuesta, term vs. whole life y cuánta cobertura necesitas de verdad. Guía clara para familias hispanas.",
    category: "seguro-de-auto",
    readMinutes: 13,
    date: "2026-08-26",
    keywords: [
      "seguro de vida para hispanos",
      "seguro de vida con ITIN",
      "seguro de vida sin seguro social",
      "cuánto cuesta un seguro de vida",
      "term life vs whole life",
    ],
  },
  {
    slug: "seguro-de-auto-illinois-inmigrantes",
    seoTitle: "Seguro de auto en Illinois para inmigrantes 2026",
    title: "Seguro de auto en Illinois para inmigrantes: requisitos y precios 2026",
    description:
      "Illinois exige 25/50/20 y da licencia sin importar estatus migratorio. Requisitos, precios en Chicago, multas y cómo bajar tu prima.",
    category: "seguro-de-auto",
    readMinutes: 12,
    date: "2026-09-02",
    keywords: [
      "seguro de auto Illinois",
      "seguro de auto Chicago hispanos",
      "licencia de manejo Illinois sin papeles",
      "requisitos seguro auto Illinois",
      "licencia estándar Illinois HB 3882",
      "seguro de auto Chicago barato",
    ],
  },
  {
    slug: "seguro-de-auto-arizona-inmigrantes",
    seoTitle: "Seguro de auto en Arizona para inmigrantes 2026",
    title: "Seguro de auto en Arizona para inmigrantes: requisitos y precios 2026",
    description:
      "Arizona exige 25/50/15, uno de los mínimos más bajos del país. Por qué te conviene subirlo, cómo asegurar sin licencia estatal y precios en Phoenix y Tucson.",
    category: "seguro-de-auto",
    readMinutes: 12,
    date: "2026-09-02",
    keywords: [
      "seguro de auto Arizona",
      "seguro de auto Phoenix hispanos",
      "seguro sin licencia Arizona",
      "requisitos seguro auto Arizona",
      "seguro de auto Phoenix precios",
      "límite de propiedad 15000 Arizona",
    ],
  },
  {
    slug: "seguro-de-casa-y-renta-inmigrantes",
    seoTitle: "Seguro de renta y de casa para inmigrantes",
    title: "Seguro de renta y de casa para inmigrantes: qué cubre y cuánto cuesta",
    description:
      "El seguro del casero no cubre tus cosas. Qué cubre el renters insurance por $18 al mes, cómo comprarlo con ITIN y qué revisar si eres dueño de casa.",
    category: "seguro-de-auto",
    readMinutes: 13,
    date: "2026-09-02",
    keywords: [
      "seguro de renta para inmigrantes",
      "renters insurance en español",
      "seguro de casa con ITIN",
      "cuánto cuesta seguro de renta",
      "seguro de inquilinos cuánto cuesta",
      "replacement cost vs actual cash value",
    ],
  },
  {
    slug: "seguro-de-auto-georgia-inmigrantes",
    seoTitle: "Seguro de auto en Georgia para inmigrantes 2026",
    title: "Seguro de auto en Georgia para inmigrantes: requisitos y precios 2026",
    description:
      "Georgia exige 25/50/25 y verifica tu seguro electrónicamente. Qué necesitas para asegurar tu carro, cuánto cuesta y qué pasa si no tienes licencia del estado.",
    category: "seguro-de-auto",
    readMinutes: 13,
    date: "2026-09-02",
    keywords: [
      "seguro de auto en Georgia",
      "seguro de carro Georgia sin licencia",
      "requisitos seguro auto Georgia",
      "seguro con ITIN Georgia",
      "GEICS Georgia verificación de seguro",
      "seguro de auto Atlanta",
    ],
  },
  {
    slug: "seguro-de-auto-nevada-inmigrantes",
    seoTitle: "Seguro de auto en Nevada para inmigrantes 2026",
    title: "Seguro de auto en Nevada para inmigrantes: requisitos y precios 2026",
    description:
      "Nevada exige 25/50/20 y da licencia de conducir sin importar tu estatus migratorio. Cómo asegurar tu carro, cuánto cuesta y qué multas evitar.",
    category: "seguro-de-auto",
    readMinutes: 12,
    date: "2026-09-02",
    keywords: [
      "seguro de auto en Nevada",
      "Driver Authorization Card Nevada",
      "requisitos seguro auto Nevada",
      "seguro de carro Las Vegas inmigrantes",
      "seguro de auto Las Vegas 2026",
      "verificación electrónica de seguro Nevada",
    ],
  },
  {
    slug: "seguro-de-auto-carolina-del-norte-inmigrantes",
    seoTitle: "Seguro de auto en Carolina del Norte: límites 2026",
    title: "Seguro de auto en Carolina del Norte: nuevos límites 50/100/50",
    description:
      "Desde julio de 2025 Carolina del Norte exige 50/100/50 más cobertura contra conductores sin seguro. Qué cambió, cuánto cuesta y cómo comprarlo con ITIN.",
    category: "seguro-de-auto",
    readMinutes: 14,
    date: "2026-09-02",
    keywords: [
      "seguro de auto Carolina del Norte",
      "límites 50/100/50 North Carolina",
      "seguro de carro NC inmigrantes",
      "requisitos seguro auto Carolina del Norte",
      "formulario DL-123 Carolina del Norte",
      "Safe Driver Incentive Plan",
    ],
  },
  {
    slug: "que-es-sr22-como-funciona",
    title: "¿Qué es un SR-22 y cómo funciona? Guía clara en español",
    description:
      "El SR-22 no es un seguro: es un certificado que tu aseguradora manda al estado. Cuándo lo necesitas, cuánto sube tu prima y por cuánto tiempo lo cargas.",
    category: "seguro-de-auto",
    readMinutes: 13,
    date: "2026-09-01",
    keywords: [
      "qué es un SR-22",
      "seguro SR22 en español",
      "SR-22 cuánto cuesta",
      "SR22 sin carro non-owner",
      "cuánto tiempo dura el SR-22",
      "FR-44 Florida y Virginia",
    ],
  },
  {
    slug: "seguro-de-salud-para-inmigrantes",
    seoTitle: "Seguro de salud para inmigrantes: opciones reales",
    title: "Seguro de salud para inmigrantes: opciones reales según tu estatus",
    description:
      "Qué cobertura de salud puedes tener con ITIN, residencia o sin papeles: Medicaid de emergencia, clínicas comunitarias FQHC, charity care y el mercado ACA.",
    category: "seguro-de-auto",
    readMinutes: 13,
    date: "2026-08-25",
    keywords: [
      "seguro de salud para inmigrantes",
      "seguro médico sin papeles",
      "clínicas gratis para indocumentados",
      "Medicaid de emergencia",
    ],
  },
  {
    slug: "seguro-de-auto-nueva-jersey-inmigrantes",
    seoTitle: "Seguro de auto en Nueva Jersey para inmigrantes",
    title:
      "Seguro de auto en Nueva Jersey para inmigrantes: nuevos mínimos 35/70/25 en 2026",
    description:
      "Los mínimos de Nueva Jersey subieron a 35/70/25 en enero de 2026. Póliza básica o estándar, PIP, licencia sin SSN y cómo pagar menos en la renovación.",
    category: "seguro-de-auto",
    readMinutes: 12,
    date: "2026-08-17",
    keywords: [
      "seguro de auto Nueva Jersey inmigrantes",
      "mínimos de seguro Nueva Jersey 35/70/25",
      "póliza básica vs estándar Nueva Jersey",
      "licencia Nueva Jersey sin SSN",
    ],
  },
  {
    slug: "seguro-de-auto-washington-inmigrantes",
    seoTitle: "Seguro de auto en Washington para inmigrantes",
    title:
      "Seguro de auto en Washington para inmigrantes: mínimos 25/50/10 y el PIP que ya tienes",
    description:
      "Washington da licencia sin Seguro Social. Mínimos legales 25/50/10, el PIP de $10,000 incluido por defecto, precios reales y cómo bajar tu prima.",
    category: "seguro-de-auto",
    readMinutes: 12,
    date: "2026-08-18",
    keywords: [
      "seguro de auto Washington inmigrantes",
      "mínimos de seguro Washington 25/50/10",
      "licencia de Washington sin SSN",
      "PIP Washington seguro de auto",
    ],
  },
  {
    slug: "seguro-de-auto-colorado-inmigrantes",
    seoTitle: "Seguro de auto en Colorado para inmigrantes",
    title:
      "Seguro de auto en Colorado para inmigrantes: licencia SB 251, granizo y mínimos 25/50/15",
    description:
      "Colorado da licencia sin estatus legal con la ley SB 251. Mínimos 25/50/15, los $5,000 de MedPay que ya tienes, granizo, robo y cómo pagar menos.",
    category: "seguro-de-auto",
    readMinutes: 12,
    date: "2026-08-18",
    keywords: [
      "seguro de auto Colorado inmigrantes",
      "licencia de Colorado SB 251",
      "mínimos de seguro Colorado 25/50/15",
      "MedPay Colorado",
    ],
  },
];
