import type { Article } from "./types";

export const impuestosArticles: Article[] = [
  {
    slug: "impuesto-remesas-1-por-ciento-2026",
    seoTitle: "Impuesto del 1% a las remesas en 2026: cómo te afecta",
    title: "Nuevo impuesto del 1% a las remesas en 2026: qué es y cómo te afecta",
    description: "Te explicamos el nuevo impuesto federal relacionado con ciertos envíos de dinero al extranjero, quién puede verse afectado y qué debes revisar antes de enviar dinero.",
    category: "impuestos",
    readMinutes: 10,
    date: "2026-09-04",
    keywords: ["impuesto a las remesas", "impuesto 1% remesas 2026", "enviar dinero impuesto", "remesas Estados Unidos", "sección 4475 remesas", "cómo evitar el impuesto a las remesas"],
  },
  {
    slug: "credito-por-hijos-itin-2026",
    seoTitle: "Crédito por Hijos con ITIN en 2026: quién califica",
    title: "Crédito por Hijos con ITIN en 2026: qué cambió y quién califica",
    description: "Qué debes revisar sobre el Crédito Tributario por Hijos en 2026, los requisitos de identificación y las situaciones en las que una familia con ITIN puede o no calificar.",
    category: "impuestos",
    readMinutes: 11,
    date: "2026-09-04",
    keywords: ["crédito por hijos ITIN", "child tax credit ITIN 2026", "crédito tributario por hijos", "taxes con ITIN hijos", "crédito por otros dependientes 500", "Schedule 8812 con ITIN"],
  },
  {
    slug: "como-sacar-itin-paso-a-paso-w7",
    seoTitle: "Cómo sacar el ITIN paso a paso: formulario W-7",
    title: "Cómo sacar tu ITIN paso a paso (Formulario W-7)",
    description: "Guía para solicitar tu ITIN con el Formulario W-7: documentos que pueden ser necesarios, formas de presentar la solicitud y qué esperar del proceso.",
    category: "impuestos",
    readMinutes: 9,
    date: "2026-08-26",
    keywords: ["cómo sacar ITIN", "formulario W-7", "solicitar ITIN paso a paso", "ITIN sin SSN", "documentos para solicitar el ITIN"],
  },
  {
    slug: "como-declarar-impuestos-con-itin-2026",
    seoTitle: "Cómo declarar impuestos con ITIN en 2026: guía completa",
    title: "Cómo declarar impuestos con ITIN en 2026",
    description: "Guía práctica para declarar impuestos con ITIN: formularios, documentos, fechas importantes y errores comunes que conviene evitar.",
    category: "impuestos",
    readMinutes: 12,
    date: "2026-09-04",
    keywords: ["declarar impuestos con ITIN", "taxes con ITIN", "cómo declarar taxes inmigrante", "declaración de impuestos 2026", "deducción estándar 2026", "formulario 1040 con ITIN"],
  },
  {
    slug: "es-seguro-declarar-impuestos-con-itin",
    seoTitle: "¿Es seguro declarar impuestos con ITIN? Mitos y realidad",
    title: "¿Es seguro declarar impuestos con ITIN? Mitos y realidad",
    description: "Aclara las dudas más comunes sobre declarar impuestos con ITIN y conoce qué información protege la ley tributaria antes de presentar tu declaración.",
    category: "impuestos",
    readMinutes: 10,
    date: "2026-09-04",
    keywords: ["es seguro declarar con ITIN", "riesgos declarar impuestos ITIN", "ITIN migración", "declarar taxes indocumentado", "IRS comparte datos con ICE", "sección 6103 confidencialidad IRS"],
  },
  {
    slug: "renovar-itin-vencido",
    seoTitle: "Cómo renovar un ITIN vencido: guía W-7",
    title: "Cómo renovar un ITIN vencido: paso a paso con el formulario W-7",
    description: "Cómo comprobar si necesitas renovar tu ITIN, qué formulario utilizar y qué pasos seguir para presentar una renovación correctamente.",
    category: "impuestos",
    readMinutes: 10,
    date: "2026-08-06",
    keywords: ["renovar ITIN vencido", "formulario W-7 renovación", "ITIN expirado qué hacer", "cómo saber si mi ITIN venció"],
  },
  {
    slug: "impuestos-trabajador-independiente-1099-itin",
    seoTitle: "Impuestos con ITIN siendo independiente: 1099 y Schedule C",
    title: "Impuestos como trabajador independiente con ITIN: 1099, Schedule C y pagos trimestrales",
    description: "Qué revisar si trabajas por tu cuenta y recibes un 1099: declaración de ingresos, gastos del negocio y pagos estimados de impuestos.",
    category: "impuestos",
    readMinutes: 13,
    date: "2026-09-04",
    keywords: ["impuestos trabajador independiente ITIN", "declarar 1099 con ITIN", "self employment tax en español", "pagos trimestrales 1040-ES", "Anexo C deducciones en español", "declarar ingresos en efectivo con ITIN"],
  },
];
