import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// The `protected-files` rule: any source file under a __ (double-underscore)
// path segment is template-managed. It reports a __ file whose sha256 no
// longer matches .runable/protected-files.json, or a __-prefixed file that
// isn't part of the template at all. Deletions are covered by konsistent's
// template-managed-files-exist rules.
//
// This rule file lives under __lint-rules/, so it protects itself: editing it
// changes its hash and fails the rule. The manifest is regenerated by
// .runable/build-template.ts (run by the sandbox image build) after an
// intentional change to a __ file.

const rulesDir = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.dirname(rulesDir);
const manifest = JSON.parse(
  readFileSync(path.join(rootDir, ".runable", "protected-files.json"), "utf8"),
);

export const protectedFiles = {
  meta: {
    type: "problem",
    docs: {
      description:
        "Files under a __ path segment are template-managed and must not be edited or created by apps.",
    },
  },
  create(context) {
    const filename = context.physicalFilename ?? context.filename;
    const rel = path.relative(rootDir, filename).split(path.sep).join("/");
    if (!rel.split("/").some((segment) => segment.startsWith("__"))) return {};

    return {
      Program(node) {
        const expected = manifest[rel];
        if (!expected) {
          context.report({
            node,
            message: `The __ prefix is reserved for template-managed files — rename ${rel} without the prefix.`,
          });
          return;
        }
        const actual = createHash("sha256").update(readFileSync(filename)).digest("hex");
        if (actual !== expected) {
          context.report({
            node,
            message: `${rel} is template-managed (__ prefix) — revert your edits and restore it from the template.`,
          });
        }
      },
    };
  },
};
